// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_array = require("rescript/lib/js/caml_array.js");

function $$new(param) {
  return {
          register_a: 0,
          register_x: 0,
          register_y: 0,
          stack_pointer: 0,
          status: 0,
          pc: 0,
          memory: Belt_Array.make(65535, 0)
        };
}

function mem_read(cpu, addr) {
  return Caml_array.get(cpu.memory, addr);
}

function mem_write(cpu, addr, data) {
  return Caml_array.set(cpu.memory, addr, data);
}

function update_zero_and_negative_flags(cpu, result) {
  cpu.status = result !== 0 ? cpu.status & 253 : cpu.status | 2;
  var match = result & 128;
  cpu.status = match !== 0 ? cpu.status | 128 : cpu.status & 127;
  
}

function update_overflow_flag_and_prune_result(cpu, result) {
  cpu.status = result > 255 ? cpu.status | 64 : cpu.status & 191;
  return result % 256;
}

function lda(cpu, param) {
  cpu.register_a = param;
  return update_zero_and_negative_flags(cpu, cpu.register_a);
}

function tax(cpu) {
  cpu.register_x = cpu.register_a;
  console.log(cpu.register_x);
  return update_zero_and_negative_flags(cpu, cpu.register_x);
}

function inx(cpu) {
  cpu.register_x = cpu.register_x + 1 | 0;
  cpu.register_x = update_overflow_flag_and_prune_result(cpu, cpu.register_x);
  return update_zero_and_negative_flags(cpu, cpu.register_x);
}

function iny(cpu) {
  cpu.register_y = cpu.register_y + 1 | 0;
  cpu.register_y = update_overflow_flag_and_prune_result(cpu, cpu.register_y);
  return update_zero_and_negative_flags(cpu, cpu.register_y);
}

function interpret(cpu, program) {
  cpu.pc = 0;
  var $$break = false;
  while(!$$break) {
    var op = Caml_array.get(program, cpu.pc);
    cpu.pc = cpu.pc + 1 | 0;
    if (op >= 171) {
      if (op !== 200) {
        if (op !== 232) {
          
        } else {
          inx(cpu);
        }
      } else {
        iny(cpu);
      }
    } else if (op >= 169) {
      if (op >= 170) {
        tax(cpu);
      } else {
        var param = Caml_array.get(program, cpu.pc);
        cpu.pc = cpu.pc + 1 | 0;
        lda(cpu, param);
      }
    } else if (op === 0) {
      $$break = true;
    }
    
  };
  
}

function load(cpu, program) {
  cpu.pc = 128;
  for(var x = 0 ,x_finish = program.length; x < x_finish; ++x){
    Caml_array.set(cpu.memory, 32768 + x | 0, Caml_array.get(program, x));
  }
  
}

var load_and_run = load;

exports.$$new = $$new;
exports.mem_read = mem_read;
exports.mem_write = mem_write;
exports.update_zero_and_negative_flags = update_zero_and_negative_flags;
exports.update_overflow_flag_and_prune_result = update_overflow_flag_and_prune_result;
exports.lda = lda;
exports.tax = tax;
exports.inx = inx;
exports.iny = iny;
exports.interpret = interpret;
exports.load = load;
exports.load_and_run = load_and_run;
/* No side effect */
