// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Cpu = require("../src/Cpu.bs.js");
var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");

Jest.describe("test_0xa9_lda_immidiate_load_data", (function (param) {
        var cpu = Cpu.$$new(undefined);
        Cpu.interpret(cpu, [
              169,
              5,
              0
            ]);
        Jest.test("register_a", (function (param) {
                return Jest.Expect.toBe(Jest.Expect.expect(cpu.register_a), 5);
              }));
        Jest.test("cpu_status_flag_2", (function (param) {
                return Jest.Expect.toBe(Jest.Expect.expect(cpu.status & 2), 0);
              }));
        return Jest.test("cpu_status_flag_7", (function (param) {
                      return Jest.Expect.toBe(Jest.Expect.expect(cpu.status & 128), 0);
                    }));
      }));

/*  Not a pure module */
